service: nodejs-es6-aws

package:
  individually: true

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
